export function DropdownGenres() {
  return (
    <div className="fixed inline-block top-24 left-52">
      <div className="flex justify-center">
        <div>
          <div className="dropdown relative">
            <button
              className="
    dropdown-toggle
    px-3
    py-1
    bg-black
    opacity-70
    border-white
    border-2
    text-white
    font-medium
    text-lg
    leading-tight
    shadow-md
    hover:bg-gray-500 hover:shadow-lg
    transition
    duration-150
    ease-in-out
    flex
    gap-4
    items-center
    whitespace-nowrap
  "
              type="button"
              id="dropdownMenuButton1"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Genres
              <svg
                aria-hidden="true"
                focusable="false"
                data-prefix="fas"
                data-icon="caret-down"
                className="w-2 ml-2"
                role="img"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 320 512"
              >
                <path
                  fill="currentColor"
                  d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"
                ></path>
              </svg>
            </button>
            <ul
              className="
    dropdown-menu
    w-[500px]
    absolute
    hidden
    bg-black
    opacity-80
    text-base
    z-50
    float-left
    py-2
    list-none
    text-left
    shadow-lg
    mt-1
    m-0
    bg-clip-padding
    border-none
  "
              aria-labelledby="dropdownMenuButton1"
            >
              <li className="flex gap-16">
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Action
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Documentories
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Sci-Fi
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Anime
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Dramas
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Shorts
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        py-2
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Asian
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Fantasy
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Sports
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Award-Winning
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Hollywood
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Thai
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        py-2
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Children & Family
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Horror
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Thriller
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Classics
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Independent
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Valentine's day
                </a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        py-2
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Comedies
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Music & Musicals
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                ></a>
              </li>
              <li className="flex gap-16">
                <a
                  className="
      flex-1
        dropdown-item
        text-sm
        px-2
        font-normal
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Crime
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                >
                  Romance
                </a>
                <a
                  className="
                flex-1
        dropdown-item
        text-sm
        py-2
        font-normal
        block
        w-full
        whitespace-nowrap
        bg-transparent
        text-white
        hover:underline
      "
                  href="#"
                ></a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
